# Generated by Django 4.1.2 on 2023-05-14 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('NombredeCategoria', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idFactura', models.IntegerField(primary_key=True, serialize=False)),
                ('Fecha', models.CharField(max_length=45, null=True)),
                ('TipodeFactura', models.CharField(max_length=45, null=True)),
                ('Descripcion_prod', models.CharField(max_length=60, null=True)),
                ('Subtotal', models.CharField(max_length=45, null=True)),
                ('Total', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45, null=True)),
                ('Apellido', models.CharField(max_length=45, null=True)),
                ('Mail', models.CharField(max_length=45, null=True)),
                ('Nro_Celular', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('idDireccion', models.IntegerField(null=True)),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tiendaEcomerce.usuario')),
                ('Pais', models.CharField(max_length=45, null=True)),
                ('Provincia', models.CharField(max_length=45, null=True)),
                ('Ciudad', models.CharField(max_length=45, null=True)),
                ('Codigo_Postal', models.CharField(max_length=45, null=True)),
                ('Calle', models.CharField(max_length=45, null=True)),
                ('Nro', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeProducto',
            fields=[
                ('idTipo_de_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=120, null=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaEcomerce.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('IdCategoria', models.CharField(max_length=45, null=True)),
                ('Nombre', models.CharField(max_length=60, null=True)),
                ('Cantidad', models.IntegerField(null=True)),
                ('Precio', models.CharField(max_length=45, null=True)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaEcomerce.categoria')),
                ('Factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaEcomerce.factura')),
            ],
        ),
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('idMetodo_Pago', models.IntegerField(primary_key=True, serialize=False)),
                ('Tipo_pago', models.CharField(max_length=45, null=True)),
                ('Nrodecuenta', models.IntegerField(null=True)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaEcomerce.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaHasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaEcomerce.factura')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaEcomerce.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='Metodo_de_Pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaEcomerce.metododepago'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='Tipo_de_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendaEcomerce.tipodeproducto'),
        ),
    ]
