# Generated by Django 4.1.2 on 2023-05-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEcomerce', '0002_rename_nombredecategoria_categoria_nombredecategoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellido',
            new_name='Apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='mail',
            new_name='Mail',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nro_Celular',
            new_name='Nro_Celular',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='idCategoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='factura',
            name='idFactura',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metododepago',
            name='idMetodo_Pago',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipodeproducto',
            name='idTipo_de_producto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
