# Generated by Django 4.1.2 on 2023-05-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEcomerce', '0003_rename_apellido_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Mail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Nro_Celular',
            new_name='nro_Celular',
        ),
    ]
