# Generated by Django 4.1.2 on 2023-05-16 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEcomerce', '0006_rename_precio_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='factura',
        ),
    ]
