# Generated by Django 4.1.2 on 2023-05-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEcomerce', '0010_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
