# Generated by Django 4.1.2 on 2023-05-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEcomerce', '0011_alter_producto_idproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='idProducto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
