# Generated by Django 4.1.2 on 2023-05-17 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEcomerce', '0012_alter_producto_idproducto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='idCategoria',
            new_name='seccion',
        ),
    ]
