# Generated by Django 4.1.2 on 2023-05-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEcomerce', '0014_alter_factura_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='idFactura',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
