# Generated by Django 4.1.2 on 2023-05-17 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaEcomerce', '0015_alter_factura_idfactura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='metodo_de_Pago',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='tipodeFactura',
        ),
    ]
